// AUTO-GENERATED by scripts/build-dart-tokens.mjs — do not edit.
// Source of truth: tokens/ramps.json + tokens/sys.json (same files that
// generate the CSS engine). Regenerate with: npm run tokens:dart
//
// ignore_for_file: prefer_single_quotes

part of '../lozenge_flutter.dart';

const double lzDefaultAccentHue = 260.48;

const Map<String, Map<String, LzOklch>> lzRamps = {
  'neutral': {'0': LzOklch(1, 0, 0), '10': LzOklch(0.987609, 0.001705, 247.84), '20': LzOklch(0.969953, 0.002872, 264.54), '30': LzOklch(0.943464, 0.005466, 274.96), '40': LzOklch(0.90965, 0.007116, 268.54), '50': LzOklch(0.827705, 0.014207, 258.35), '60': LzOklch(0.786794, 0.017427, 259.42), '70': LzOklch(0.745372, 0.020757, 260.17), '80': LzOklch(0.703399, 0.02421, 260.71), '90': LzOklch(0.660833, 0.027801, 261.11), '100': LzOklch(0.617229, 0.033436, 260.66), '200': LzOklch(0.566897, 0.035593, 261.65), '300': LzOklch(0.528712, 0.041582, 261.16), '400': LzOklch(0.483261, 0.046016, 261.31), '500': LzOklch(0.436925, 0.050746, 261.39), '600': LzOklch(0.389644, 0.05582, 261.4), '700': LzOklch(0.340738, 0.061767, 260.38), '800': LzOklch(0.291675, 0.067561, 260.37), '900': LzOklch(0.242159, 0.073495, 260.41)},
  'darkNeutral': {'0': LzOklch(0.214896, 0.008484, 240.3), '100': LzOklch(0.245357, 0.009649, 248.22), '200': LzOklch(0.269413, 0.01036, 242.08), '250': LzOklch(0.2974, 0.012388, 243.26), '300': LzOklch(0.317294, 0.01582, 248.32), '350': LzOklch(0.370649, 0.019558, 248.35), '400': LzOklch(0.422555, 0.021038, 248.32), '500': LzOklch(0.50639, 0.025655, 244.16), '600': LzOklch(0.60599, 0.033898, 249.89), '700': LzOklch(0.682908, 0.029197, 249.97), '800': LzOklch(0.741487, 0.026781, 250.03), '900': LzOklch(0.808807, 0.022628, 250.26), '1000': LzOklch(0.856022, 0.017668, 248.03), '1100': LzOklch(0.916033, 0.010424, 247.94), 'deep': LzOklch(0.180862, 0.00521, 248.12)},
  'blue': {'50': LzOklch(0.936376, 0.030519, 258.94), '75': LzOklch(0.860526, 0.06976, 255.18), '100': LzOklch(0.685072, 0.168083, 256), '200': LzOklch(0.627946, 0.202013, 257.4), '300': LzOklch(0.561585, 0.241945, 260.95), '400': LzOklch(0.480172, 0.201153, 260.48), '500': LzOklch(0.425067, 0.164468, 259.85)},
  'red': {'50': LzOklch(0.95467, 0.0229, 34.3), '75': LzOklch(0.854775, 0.079987, 34.05), '100': LzOklch(0.764732, 0.14184, 35), '200': LzOklch(0.719651, 0.177109, 34.97), '300': LzOklch(0.679027, 0.211368, 34.02), '400': LzOklch(0.589855, 0.209951, 33.44), '500': LzOklch(0.521834, 0.192331, 33.04)},
  'yellow': {'50': LzOklch(0.983661, 0.026711, 95.33), '75': LzOklch(0.952717, 0.079228, 95.94), '100': LzOklch(0.918696, 0.123006, 94), '200': LzOklch(0.849795, 0.173865, 86.55), '300': LzOklch(0.803371, 0.170443, 73.79), '400': LzOklch(0.77267, 0.169096, 62.8), '500': LzOklch(0.748947, 0.179611, 57.82)},
  'green': {'50': LzOklch(0.969336, 0.031227, 163.26), '75': LzOklch(0.911785, 0.088637, 162.91), '100': LzOklch(0.877465, 0.131345, 164.35), '200': LzOklch(0.798792, 0.1393, 162.79), '300': LzOklch(0.685347, 0.134603, 160.83), '400': LzOklch(0.550605, 0.122266, 161.18), '500': LzOklch(0.450947, 0.099094, 161.87)},
  'purple': {'50': LzOklch(0.935549, 0.033818, 293.08), '75': LzOklch(0.805304, 0.084445, 292.03), '100': LzOklch(0.683799, 0.110802, 290.4), '200': LzOklch(0.627427, 0.144172, 289.05), '300': LzOklch(0.519717, 0.162626, 286.5), '400': LzOklch(0.457536, 0.158314, 284.9), '500': LzOklch(0.394982, 0.153621, 283.32)},
  'teal': {'50': LzOklch(0.975916, 0.023336, 206.62), '75': LzOklch(0.929429, 0.06705, 207.75), '100': LzOklch(0.855522, 0.099803, 208.37), '200': LzOklch(0.763019, 0.134252, 214.19), '300': LzOklch(0.721492, 0.128683, 216.76), '400': LzOklch(0.658952, 0.116863, 215.74), '500': LzOklch(0.592794, 0.105345, 216.12)},
};

const Map<String, LzTokenSchemes> lzSysTokens = {
  'text': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.800', k: -0.1), dark: LzTokenDef(ref: 'darkNeutral.1100', k: 0.08)),
  'text-subtle': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.300', k: -0.1), dark: LzTokenDef(ref: 'darkNeutral.800', k: 0.1)),
  'text-subtlest': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.100', k: -0.1), dark: LzTokenDef(ref: 'darkNeutral.700', k: 0.12)),
  'text-disabled': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.70'), dark: LzTokenDef(ref: 'darkNeutral.500')),
  'text-inverse': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'darkNeutral.deep')),
  'text-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'neutral.0')),
  'link': LzTokenSchemes(light: LzTokenDef(ref: 'accent.400', k: -0.08, ck: -0.25), dark: LzTokenDef(ref: 'accent.100', k: 0.08, ck: -0.25)),
  'link-hover': LzTokenSchemes(light: LzTokenDef(ref: 'accent.300', lShift: -0.04, k: -0.08, ck: -0.25, cScale: 0.82), dark: LzTokenDef(ref: 'accent.75', k: 0.05, ck: -0.25)),
  'link-active': LzTokenSchemes(light: LzTokenDef(ref: 'accent.500', k: -0.06, ck: -0.2), dark: LzTokenDef(ref: 'accent.200', k: 0.06, ck: -0.2)),
  'surface': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'darkNeutral.100', k: -0.02)),
  'surface-sunken': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.20', k: 0.02), dark: LzTokenDef(ref: 'darkNeutral.deep', k: -0.01)),
  'surface-raised': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'darkNeutral.200', k: -0.01)),
  'surface-overlay': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'darkNeutral.250', k: -0.01)),
  'border': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.40', k: -0.3), dark: LzTokenDef(ref: 'darkNeutral.350', k: 0.3)),
  'separator': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.30', k: -0.2), dark: LzTokenDef(ref: 'darkNeutral.300', k: 0.2)),
  'focus-ring': LzTokenSchemes(light: LzTokenDef(ref: 'accent.100', lShift: -0.08, k: -0.06, ck: -0.2), dark: LzTokenDef(ref: 'accent.100', k: 0.05, ck: -0.2)),
  'selected-bg': LzTokenSchemes(light: LzTokenDef(ref: 'accent.50'), dark: LzTokenDef(ref: 'accent.400', alpha: 0.18)),
  'selected-text': LzTokenSchemes(light: LzTokenDef(ref: 'accent.400', k: -0.08, ck: -0.25), dark: LzTokenDef(ref: 'accent.100', k: 0.08, ck: -0.25)),
  'interaction-bg': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.900', alpha: 0.04), dark: LzTokenDef(ref: 'darkNeutral.1100', alpha: 0.07)),
  'interaction-hovered': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.900', alpha: 0.09), dark: LzTokenDef(ref: 'darkNeutral.1100', alpha: 0.12)),
  'interaction-pressed': LzTokenSchemes(light: LzTokenDef(ref: 'accent.75', alpha: 0.6), dark: LzTokenDef(ref: 'accent.400', alpha: 0.35)),
  'blanket': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.900', alpha: 0.54), dark: LzTokenDef(ref: 'darkNeutral.deep', alpha: 0.62)),
  'accent-bold': LzTokenSchemes(light: LzTokenDef(ref: 'accent.400', k: -0.05, ck: -0.2), dark: LzTokenDef(ref: 'accent.400', k: -0.04, ck: -0.2)),
  'accent-bold-hovered': LzTokenSchemes(light: LzTokenDef(ref: 'accent.300', k: -0.05, ck: -0.2), dark: LzTokenDef(ref: 'accent.300', k: -0.04, ck: -0.2)),
  'accent-bold-pressed': LzTokenSchemes(light: LzTokenDef(ref: 'accent.500', k: -0.04, ck: -0.2), dark: LzTokenDef(ref: 'accent.500', k: -0.03, ck: -0.2)),
  'danger-bold': LzTokenSchemes(light: LzTokenDef(ref: 'red.400', k: -0.05, ck: -0.15), dark: LzTokenDef(ref: 'red.400', k: -0.05, ck: -0.15)),
  'danger-bold-hovered': LzTokenSchemes(light: LzTokenDef(ref: 'red.300', k: -0.05, ck: -0.15), dark: LzTokenDef(ref: 'red.300', k: -0.05, ck: -0.15)),
  'danger-bold-pressed': LzTokenSchemes(light: LzTokenDef(ref: 'red.500', k: -0.04, ck: -0.15), dark: LzTokenDef(ref: 'red.500', k: -0.03, ck: -0.15)),
  'warning-bold': LzTokenSchemes(light: LzTokenDef(ref: 'yellow.300', k: 0.02, ck: -0.12), dark: LzTokenDef(ref: 'yellow.300', k: 0.02, ck: -0.12)),
  'warning-bold-hovered': LzTokenSchemes(light: LzTokenDef(ref: 'yellow.400', k: 0.02, ck: -0.12), dark: LzTokenDef(ref: 'yellow.400', k: 0.02, ck: -0.12)),
  'warning-bold-pressed': LzTokenSchemes(light: LzTokenDef(ref: 'yellow.500', k: 0.02, ck: -0.12), dark: LzTokenDef(ref: 'yellow.500', k: 0.02, ck: -0.12)),
  'input-bg': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.10'), dark: LzTokenDef(ref: 'darkNeutral.0')),
  'input-hover-bg': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.30'), dark: LzTokenDef(ref: 'darkNeutral.250')),
  'surface-raised-hovered': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.10'), dark: LzTokenDef(ref: 'darkNeutral.300')),
  'toggle-off': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.200'), dark: LzTokenDef(ref: 'darkNeutral.400')),
  'track': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.40', k: -0.08), dark: LzTokenDef(ref: 'darkNeutral.350', k: 0.08)),
  'tooltip-bg': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.800'), dark: LzTokenDef(ref: 'darkNeutral.1000')),
  'tooltip-text': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'darkNeutral.deep')),
  'status-neutral-subtle-bg': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.30'), dark: LzTokenDef(ref: 'darkNeutral.350')),
  'status-neutral-subtle-text': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.500', k: -0.1), dark: LzTokenDef(ref: 'darkNeutral.1000', k: 0.06)),
  'status-neutral-bold-bg': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.500', k: -0.06), dark: LzTokenDef(ref: 'darkNeutral.700', k: 0.06)),
  'status-neutral-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'darkNeutral.deep')),
  'status-info-subtle-bg': LzTokenSchemes(light: LzTokenDef(ref: 'accent.50'), dark: LzTokenDef(ref: 'accent.500', alpha: 0.32)),
  'status-info-subtle-text': LzTokenSchemes(light: LzTokenDef(ref: 'accent.500', k: -0.08, ck: -0.2), dark: LzTokenDef(ref: 'accent.100', k: 0.07, ck: -0.2)),
  'status-info-bold-bg': LzTokenSchemes(light: LzTokenDef(ref: 'accent.400', k: -0.05, ck: -0.2), dark: LzTokenDef(ref: 'accent.400', k: -0.04, ck: -0.2)),
  'status-info-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'neutral.0')),
  'status-warning-subtle-bg': LzTokenSchemes(light: LzTokenDef(ref: 'yellow.75'), dark: LzTokenDef(ref: 'yellow.500', alpha: 0.28)),
  'status-warning-subtle-text': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.800', k: -0.08), dark: LzTokenDef(ref: 'yellow.100', k: 0.05, ck: -0.2)),
  'status-warning-bold-bg': LzTokenSchemes(light: LzTokenDef(ref: 'yellow.500', k: 0.03, ck: -0.12), dark: LzTokenDef(ref: 'yellow.400', k: 0.03, ck: -0.12)),
  'status-warning-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.800', k: -0.08), dark: LzTokenDef(ref: 'darkNeutral.deep')),
  'status-danger-subtle-bg': LzTokenSchemes(light: LzTokenDef(ref: 'red.50'), dark: LzTokenDef(ref: 'red.500', alpha: 0.3)),
  'status-danger-subtle-text': LzTokenSchemes(light: LzTokenDef(ref: 'red.500', k: -0.08, ck: -0.2), dark: LzTokenDef(ref: 'red.100', k: 0.06, ck: -0.2)),
  'status-danger-bold-bg': LzTokenSchemes(light: LzTokenDef(ref: 'red.400', k: -0.05, ck: -0.15), dark: LzTokenDef(ref: 'red.400', k: -0.05, ck: -0.15)),
  'status-danger-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'neutral.0')),
  'status-success-subtle-bg': LzTokenSchemes(light: LzTokenDef(ref: 'green.50'), dark: LzTokenDef(ref: 'green.500', alpha: 0.3)),
  'status-success-subtle-text': LzTokenSchemes(light: LzTokenDef(ref: 'green.500', k: -0.08, ck: -0.2), dark: LzTokenDef(ref: 'green.200', k: 0.06, ck: -0.2)),
  'status-success-bold-bg': LzTokenSchemes(light: LzTokenDef(ref: 'green.400', k: -0.05, ck: -0.15), dark: LzTokenDef(ref: 'green.400', k: -0.05, ck: -0.15)),
  'status-success-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'neutral.0')),
  'status-discovery-subtle-bg': LzTokenSchemes(light: LzTokenDef(ref: 'purple.50'), dark: LzTokenDef(ref: 'purple.500', alpha: 0.34)),
  'status-discovery-subtle-text': LzTokenSchemes(light: LzTokenDef(ref: 'purple.500', k: -0.08, ck: -0.2), dark: LzTokenDef(ref: 'purple.100', k: 0.07, ck: -0.2)),
  'status-discovery-bold-bg': LzTokenSchemes(light: LzTokenDef(ref: 'purple.400', k: -0.05, ck: -0.15), dark: LzTokenDef(ref: 'purple.300', k: -0.04, ck: -0.15)),
  'status-discovery-on-bold': LzTokenSchemes(light: LzTokenDef(ref: 'neutral.0'), dark: LzTokenDef(ref: 'neutral.0')),
};

/// Lozenge status-variant families, as used by lozenges/messages/flags.
const Map<String, String> lzLozengeVariants = {
  'default': 'neutral', 'inprogress': 'info', 'moved': 'warning',
  'new': 'discovery', 'removed': 'danger', 'success': 'success',
};

/// Motion tokens (mirrors --lz-motion-* / --lz-ease-*).
class LzMotion {
  static const fast = Duration(milliseconds: 100);
  static const medium = Duration(milliseconds: 200);
  static const slow = Duration(milliseconds: 300);
  static const deliberate = Duration(milliseconds: 700);
  static const standard = Cubic(0.2, 0, 0, 1);
  static const entrance = Cubic(0.15, 1, 0.3, 1);
  static const exit = Cubic(0.6, 0, 1, 0.6);
}

/// Typed accessors for every system token.
extension LzSysColors on LzThemeData {
  Color get text => resolve('text');
  Color get textSubtle => resolve('text-subtle');
  Color get textSubtlest => resolve('text-subtlest');
  Color get textDisabled => resolve('text-disabled');
  Color get textInverse => resolve('text-inverse');
  Color get textOnBold => resolve('text-on-bold');
  Color get link => resolve('link');
  Color get linkHover => resolve('link-hover');
  Color get linkActive => resolve('link-active');
  Color get surface => resolve('surface');
  Color get surfaceSunken => resolve('surface-sunken');
  Color get surfaceRaised => resolve('surface-raised');
  Color get surfaceOverlay => resolve('surface-overlay');
  Color get border => resolve('border');
  Color get separator => resolve('separator');
  Color get focusRing => resolve('focus-ring');
  Color get selectedBg => resolve('selected-bg');
  Color get selectedText => resolve('selected-text');
  Color get interactionBg => resolve('interaction-bg');
  Color get interactionHovered => resolve('interaction-hovered');
  Color get interactionPressed => resolve('interaction-pressed');
  Color get blanket => resolve('blanket');
  Color get accentBold => resolve('accent-bold');
  Color get accentBoldHovered => resolve('accent-bold-hovered');
  Color get accentBoldPressed => resolve('accent-bold-pressed');
  Color get dangerBold => resolve('danger-bold');
  Color get dangerBoldHovered => resolve('danger-bold-hovered');
  Color get dangerBoldPressed => resolve('danger-bold-pressed');
  Color get warningBold => resolve('warning-bold');
  Color get warningBoldHovered => resolve('warning-bold-hovered');
  Color get warningBoldPressed => resolve('warning-bold-pressed');
  Color get inputBg => resolve('input-bg');
  Color get inputHoverBg => resolve('input-hover-bg');
  Color get surfaceRaisedHovered => resolve('surface-raised-hovered');
  Color get toggleOff => resolve('toggle-off');
  Color get track => resolve('track');
  Color get tooltipBg => resolve('tooltip-bg');
  Color get tooltipText => resolve('tooltip-text');
  Color get statusNeutralSubtleBg => resolve('status-neutral-subtle-bg');
  Color get statusNeutralSubtleText => resolve('status-neutral-subtle-text');
  Color get statusNeutralBoldBg => resolve('status-neutral-bold-bg');
  Color get statusNeutralOnBold => resolve('status-neutral-on-bold');
  Color get statusInfoSubtleBg => resolve('status-info-subtle-bg');
  Color get statusInfoSubtleText => resolve('status-info-subtle-text');
  Color get statusInfoBoldBg => resolve('status-info-bold-bg');
  Color get statusInfoOnBold => resolve('status-info-on-bold');
  Color get statusWarningSubtleBg => resolve('status-warning-subtle-bg');
  Color get statusWarningSubtleText => resolve('status-warning-subtle-text');
  Color get statusWarningBoldBg => resolve('status-warning-bold-bg');
  Color get statusWarningOnBold => resolve('status-warning-on-bold');
  Color get statusDangerSubtleBg => resolve('status-danger-subtle-bg');
  Color get statusDangerSubtleText => resolve('status-danger-subtle-text');
  Color get statusDangerBoldBg => resolve('status-danger-bold-bg');
  Color get statusDangerOnBold => resolve('status-danger-on-bold');
  Color get statusSuccessSubtleBg => resolve('status-success-subtle-bg');
  Color get statusSuccessSubtleText => resolve('status-success-subtle-text');
  Color get statusSuccessBoldBg => resolve('status-success-bold-bg');
  Color get statusSuccessOnBold => resolve('status-success-on-bold');
  Color get statusDiscoverySubtleBg => resolve('status-discovery-subtle-bg');
  Color get statusDiscoverySubtleText => resolve('status-discovery-subtle-text');
  Color get statusDiscoveryBoldBg => resolve('status-discovery-bold-bg');
  Color get statusDiscoveryOnBold => resolve('status-discovery-on-bold');
}
