// Cross-engine proof: the Dart resolver must reproduce the JS resolver's
// output (test/fixtures/resolved_colors.json, generated by
// scripts/build-dart-tokens.mjs from the shared resolve.mjs) within ±2/255
// per channel. If this fails, the web and Flutter engines have drifted.
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:lozenge_flutter/lozenge_flutter.dart';

void main() {
  final entries = (jsonDecode(
    File('test/fixtures/resolved_colors.json').readAsStringSync(),
  ) as List)
      .cast<Map<String, dynamic>>();

  test('all ${entries.length} fixture colors match the JS engine', () {
    const tol = 2;
    final themes = <String, LzThemeData>{};
    final failures = <String>[];

    for (final e in entries) {
      final key = '${e['scheme']}|${e['dial']}|${e['hue']}';
      final theme = themes.putIfAbsent(
        key,
        () => LzThemeData(
          dark: e['scheme'] == 'dark',
          contrast: (e['dial'] as num).toDouble(),
          accentHue: (e['hue'] as num).toDouble(),
        ),
      );
      final Color got = theme.resolve(e['token'] as String);
      final rgba = (e['rgba'] as List).cast<num>();
      final want = [
        (rgba[0] * 255).round(),
        (rgba[1] * 255).round(),
        (rgba[2] * 255).round(),
        (rgba[3] * 255).round(),
      ];
      final gotCh = [
        (got.r * 255).round(),
        (got.g * 255).round(),
        (got.b * 255).round(),
        (got.a * 255).round(),
      ];
      for (var i = 0; i < 4; i++) {
        if ((gotCh[i] - want[i]).abs() > tol) {
          failures.add(
              '${e['token']} [$key] ch$i: got ${gotCh[i]}, want ${want[i]}');
          break;
        }
      }
    }

    expect(failures, isEmpty,
        reason:
            '${failures.length} drifted:\n${failures.take(20).join('\n')}');
  });
}
