#!/usr/bin/env node
// Generates the Lozenge token engine from tokens/ramps.json + tokens/sys.json:
//   scss/generated/_engine.scss  — @property axes, OKLCH ref tier, parametric
//                                  accent ramp, sys tier (light+dark) with
//                                  contrast-dial math, motion tokens, gates
//   tokens/lozenge.tokens.json   — DTCG v2025.10 export
// The same sys.json is consumed numerically by check-contrast.mjs.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { converter } from "culori";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ramps = JSON.parse(readFileSync(join(root, "tokens/ramps.json"), "utf8"));
const sys = JSON.parse(readFileSync(join(root, "tokens/sys.json"), "utf8"));
delete ramps.$comment;

const toOklch = converter("oklch");

const fmt = (n, dp = 4) => Number(n.toFixed(dp));

function oklchOf(hex) {
  const c = toOklch(hex);
  return { l: fmt(c.l), c: fmt(c.c ?? 0), h: fmt(c.h ?? 0, 2) };
}

const refVar = (ref) => {
  const [ramp, step] = ref.split(".");
  return `--lz-ref-${ramp.toLowerCase()}-${step}`;
};

// ---------------------------------------------------------------- ref tier
let refCss = "";
for (const [ramp, steps] of Object.entries(ramps)) {
  for (const [step, hex] of Object.entries(steps)) {
    const { l, c, h } = oklchOf(hex);
    refCss += `  --lz-ref-${ramp.toLowerCase()}-${step}: oklch(${l} ${c} ${h});\n`;
  }
}

// Parametric accent ramp: per-step L/C lifted from the blue ramp, hue and
// chroma-scale supplied by the --lz-accent-* dials (defaults = Jira blue).
const blue400 = oklchOf(ramps.blue["400"]);
let accentCss = "";
for (const [step, hex] of Object.entries(ramps.blue)) {
  const { l, c } = oklchOf(hex);
  accentCss += `  --lz-ref-accent-${step}: oklch(${l} calc(${c} * var(--lz-accent-chroma)) var(--lz-accent-hue));\n`;
}

// ---------------------------------------------------------------- sys tier
function sysDecl(name, def) {
  const v = refVar(def.ref);
  const hasShift = def.lShift !== undefined && def.lShift !== 0;
  const hasK = def.k !== undefined && def.k !== 0;
  const hasCk = def.ck !== undefined && def.ck !== 0;
  const hasA = def.alpha !== undefined;
  if (!hasShift && !hasK && !hasCk && !hasA)
    return `  --lz-sys-${name}: var(${v});\n`;
  const lTerms = [
    "l",
    hasShift ? `${def.lShift}` : null,
    hasK ? `${def.k} * var(--lz-contrast)` : null,
  ].filter(Boolean);
  const l =
    lTerms.length > 1 ? `clamp(0, calc(${lTerms.join(" + ")}), 1)` : "l";
  // Chroma gate scales with |dial| so both extremes stay inside sRGB;
  // cScale is a static multiplier for tokens whose L shift leaves the
  // source chroma outside the envelope even at rest.
  const cs = def.cScale ?? 1;
  const c =
    hasCk || cs !== 1
      ? `max(0, calc(c * ${cs} * (1 + ${def.ck ?? 0} * abs(var(--lz-contrast)))))`
      : "c";
  const a = hasA ? ` / ${def.alpha}` : "";
  return `  --lz-sys-${name}: oklch(from var(${v}) ${l} ${c} h${a});\n`;
}

let sysLight = "";
let sysDark = "";
for (const [name, schemes] of Object.entries(sys.tokens)) {
  sysLight += sysDecl(name, schemes.light);
  sysDark += sysDecl(name, schemes.dark);
}

// ---------------------------------------------------------------- assemble
const darkBlock = `  color-scheme: dark;\n${sysDark}`;

const engine = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit.
 * Source of truth: tokens/ramps.json + tokens/sys.json. */

/* ---- theme axes (numeric, animatable, device-drivable) ---- */
@property --lz-contrast {
  syntax: "<number>";
  inherits: true;
  initial-value: 0;
}
@property --lz-accent-hue {
  syntax: "<number>";
  inherits: true;
  initial-value: ${blue400.h};
}
@property --lz-accent-chroma {
  syntax: "<number>";
  inherits: true;
  initial-value: 1;
}
@property --lz-glass {
  syntax: "<number>";
  inherits: true;
  initial-value: 1;
}

:root {
  --lz-contrast: 0;
  --lz-accent-hue: ${blue400.h};
  --lz-accent-chroma: 1;
  --lz-glass: 1;

  /* ---- reference tier ---- */
${refCss}
  /* ---- parametric accent ramp (defaults = blue) ---- */
${accentCss}
  /* ---- motion tokens ---- */
  --lz-motion-fast: 100ms;
  --lz-motion-medium: 200ms;
  --lz-motion-slow: 300ms;
  --lz-motion-deliberate: 700ms;
  --lz-ease-standard: cubic-bezier(0.2, 0, 0, 1);
  --lz-ease-entrance: cubic-bezier(0.15, 1, 0.3, 1);
  --lz-ease-exit: cubic-bezier(0.6, 0, 1, 0.6);

  /* ---- material (glass) recipe: alpha rises toward opaque as the
     contrast dial rises; --lz-glass 0 collapses to solid ---- */
  --lz-material-alpha: clamp(0, calc(1 - var(--lz-glass) * 0.28 * (1 - clamp(0, var(--lz-contrast), 1))), 1);
  --lz-material-blur: calc(var(--lz-glass) * 16px);
  --lz-material-saturate: calc(1 + var(--lz-glass) * 0.4);

  /* ---- sys tier: light scheme ---- */
  color-scheme: light;
${sysLight}}

[data-theme="dark"] {
${darkBlock}}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]):not([data-theme="dark"]) {
${darkBlock}  }
}

/* OS contrast preferences map onto the dial (inline/user styles still win). */
@media (prefers-contrast: more) {
  :root {
    --lz-contrast: 0.6;
    --lz-glass: 0;
  }
}
@media (prefers-contrast: less) {
  :root {
    --lz-contrast: -0.35;
  }
}
@media (prefers-reduced-transparency: reduce) {
  :root {
    --lz-glass: 0;
  }
}
@media (forced-colors: active) {
  :root {
    --lz-glass: 0;
  }
}
`;

mkdirSync(join(root, "scss/generated"), { recursive: true });
writeFileSync(join(root, "scss/generated/_engine.scss"), engine);

// ---------------------------------------------------------------- DTCG
const dtcg = { $schema: "https://tr.designtokens.org/format/", color: {} };
for (const [ramp, steps] of Object.entries(ramps)) {
  dtcg.color[ramp] = {};
  for (const [step, hex] of Object.entries(steps)) {
    const { l, c, h } = oklchOf(hex);
    dtcg.color[ramp][step] = {
      $type: "color",
      $value: {
        colorSpace: "oklch",
        components: [l, c, h],
        alpha: 1,
        hex,
      },
    };
  }
}
dtcg.color.semantic = {};
for (const [name, schemes] of Object.entries(sys.tokens)) {
  dtcg.color.semantic[name] = {
    $type: "color",
    $value: `{color.${schemes.light.ref.replace(".", ".")}}`,
    $extensions: {
      "net.jethachan.lozenge": {
        schemes,
        note: "Resolved at runtime via CSS relative color; see tokens/sys.json",
      },
    },
  };
}
writeFileSync(
  join(root, "tokens/lozenge.tokens.json"),
  JSON.stringify(dtcg, null, 2) + "\n"
);

console.log(
  `engine: ${Object.keys(ramps).length} ramps, ${Object.keys(sys.tokens).length} sys tokens → scss/generated/_engine.scss + tokens/lozenge.tokens.json`
);
